### ISSUE TITLE
Message text misaligned

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-ui-default#17]
It looks like the message text is misaligned (a tad too high) compared to the "bubbles" at the start of the line and the "at line X col X" text.

![image](https://cloud.githubusercontent.com/assets/427137/12096911/7ced9f20-b2cd-11e5-9ab3-26ac23228c14.png)

**Comment by Arcanemagus** [comment]
Looks like "Linter" and "___ Issues" aren't aligned as well.

**Comment by steelbrain** [comment]
For the record, the messages are aligned for me on one-dark ui and syntax themes

![image](http://i.imgur.com/RFuZOZ6.png)

**Comment by Arcanemagus** [comment]
I'm still seeing issues on one-dark ui+syntax:
![image](https://cloud.githubusercontent.com/assets/427137/12097260/8219ef24-b2cf-11e5-8b2b-94f622d7d122.png)

I'm on Atom v1.4.0-beta3 btw.

**Comment by Arcanemagus** [comment]
Filing separate issues for each alignment issue, no sense in this one ballooning out of control :stuck_out_tongue:.

**Comment by Arcanemagus** [comment]
**Windows:**
![image](https://cloud.githubusercontent.com/assets/427137/12099131/68c97fd8-b2db-11e5-9f8d-89ecb2144c2c.png)

The bright blue line in that image is the pixel below the text starting at <kbd>ESLint</kbd> on Windows. As you can see the 3 bubbles are all aligned, but the message text is slightly higher, while the location text is slightly _lower_.

**Ubuntu:**
![image](https://cloud.githubusercontent.com/assets/427137/12099262/18af29fc-b2dc-11e5-985d-954954c0660a.png)

Looks like this might be aligned properly, I initially thought mine was a bit off with the buttons, but it seems there is a slight drop shadow being added here that doesn't show up on the black background for the other text.

Testing Windows with a blank profile next.

**Comment by Arcanemagus** [comment]
Update, after setting Ubuntu to one-dark the location is definitely misaligned:
![image](https://cloud.githubusercontent.com/assets/427137/12099515/e788e8e8-b2dd-11e5-9228-cb37e1f0a786.png)

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-ui-default/pull/40
