### ISSUE TITLE
Minimize and close buttons not aligned

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-ui-default#18]
The minimize button is a few pixels below the bottom of the X button:
![image](https://cloud.githubusercontent.com/assets/427137/12097334/01319ff0-b2d0-11e5-8630-48a723696c8c.png)

Atom v1.4.0-beta3
Windows 10 x64

Found with both one-dark ui+syntax and seti ui+syntax.

**Comment by Arcanemagus** [comment]
I'm seeing this on Ubuntu on one-dark as well.

**Comment by steelbrain** [comment]
Nevermind

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-ui-default/pull/40
