### ISSUE TITLE
Make the title bar smaller

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-ui-default#20]
Currently the title bar is quite large, taking up ~2.5 messages worth of vertical space. As it always shows no matter what this should be as small as possible to reduce the amount of space used by this package.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-ui-default/pull/38

**Comment by Arcanemagus** [comment]
Yep, it's _much_ better after that landed, thanks @KaneezIqbal!
