### ISSUE TITLE
Mac: allow Cmd-C to copy error messages from linter error panel

### ISSUE THREAD

**Issue by pascalpp** [AtomLinter/linter-ui-default#33]
![image](https://cloud.githubusercontent.com/assets/1355312/12893718/ba52d57a-ce60-11e5-8e8e-c4fc9c1ee392.png)

When trying to copy text from the linter error panel, Ctrl-C works, even on a mac. But really it should work with Cmd-C.

**Comment by steelbrain** [comment]
We also need a context menu thing for there
