### ISSUE TITLE
Implement Fixes using intentions:list API

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-ui-default#44]
Just like the title says

**Comment by pke** [comment]
Any hints how to start and debug this change? Never wrote for atom and the tutorial on their page does not help much: https://atom.io/docs/v1.0.11/hacking-atom-package-word-count

I have cloned this package with `apm develop linter-ui-default` and started `atom -d .` in the package folder.
Now I imagine to test my changes to `message.js` with the eslint package also loaded and provoke a rule violation to make my modified message appear. But how? Any hints?

**Comment by steelbrain** [comment]
@pke The instructions of checking out this package are in the README

**Comment by steelbrain** [comment]
@pke If you can wait for a few weeks, I'll implement this myself :)

**Comment by pke** [comment]
Well I certainly can wait, but it looks like an easy fix once I have the setup running.

**Comment by steelbrain** [comment]
There is a working implementation in https://github.com/AtomLinter/linter-ui-default/pull/50
